// <auto-generated />
namespace KeyHub.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ef6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ef6));
        
        string IMigrationMetadata.Id
        {
            get { return "201406210148508_ef6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
