// <auto-generated />
namespace KeyHub.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class identitydbcontext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identitydbcontext));
        
        string IMigrationMetadata.Id
        {
            get { return "201406210220270_identitydbcontext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
